### ISSUE TITLE
Reject method

### ISSUE THREAD

**Issue by robbash** [bschmitt/laravel-amqp#1]
Hi Björn,

I've added a `reject` method to your consumer class to requeue messages if execution/consumption fails. Not sure of you want  it in your lib or not.

```
    /**
     * Rejects a message and requeues it if wanted.
     *
     * @param Message $message
     * @param bool $requeue
     */
    public function reject($message, $requeue)
    {
        $message->delivery_info['channel']->basic_reject($message->delivery_info['delivery_tag'], $requeue);
    }
```

Cheers,
Rob

**Comment by bschmitt** [comment]
Thank you! Do you have a pull request for that? Otherwise I can add it directly. 

Btw, did you use Lumen or Laravel? I didn't had the time to create a service provider for Laravel yet.

**Comment by robbash** [comment]
No, I don't have a PR as we cloned it into our company git. I could create one but probably it's easier if you would add it directly.
I'm using Lumen. ;)
