### ISSUE TITLE
Unable to Connect

### ISSUE THREAD

**Issue by arunappulal** [bschmitt/laravel-amqp#12]
I'm Using Laravel 5.2. and where should I add my login credentials of RabbitMQ?.

stream_socket_client(): unable to connect to tcp://: (Failed to parse address &quot;:&quot;)

**Comment by bschmitt** [comment]
Just copy the following file to *config/amqp.php* and change the values to your needs.

https://github.com/bschmitt/laravel-amqp/blob/master/config/amqp.php

Does this help?

**Comment by arunappulal** [comment]
Yes!.Thanks a lot @bschmitt ...
