### ISSUE TITLE
laravel 5.3 support

### ISSUE THREAD

**Issue by AidasK** [bschmitt/laravel-amqp#15]

**Comment by arunappulal** [comment]
Problem 1
    - Conclusion: don't install laravel/framework v5.3.10
    - Conclusion: remove laravel/framework v5.3.9
    - Conclusion: don't install laravel/framework v5.3.9
    - Conclusion: don't install laravel/framework v5.3.8
    - Conclusion: don't install laravel/framework v5.3.7
    - Conclusion: don't install laravel/framework v5.3.6
    - Conclusion: don't install laravel/framework v5.3.5
    - Conclusion: don't install laravel/framework v5.3.4
    - Conclusion: don't install laravel/framework v5.3.3
    - Installation request for bschmitt/laravel-amqp 1.* -> satisfiable by bschm                                                                                                                itt/laravel-amqp[1.2.1].
    - Conclusion: don't install laravel/framework v5.3.2
    - Conclusion: don't install laravel/framework v5.3.1
    - bschmitt/laravel-amqp 1.2.1 requires illuminate/support >=5.1 <5.3 -> sati                                                                                                                sfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22                                                                                                                , v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19,                                                                                                                 v5.2.21, v5.2.24, v5.2.25, v5.2.26, v

**Comment by AidasK** [comment]
you only need to change this line https://github.com/bschmitt/laravel-amqp/blob/master/composer.json#L30

**Comment by bschmitt** [comment]
Thanks again @AidasK for providing the fix. A new release has been created.
<img width="910" alt="bildschirmfoto 2016-09-22 um 23 17 51" src="https://cloud.githubusercontent.com/assets/239644/18766526/f407eedc-811a-11e6-9c61-1704c9061692.png">
