### ISSUE TITLE
Support for channel->basic_qos

### ISSUE THREAD

**Issue by fl0v** [bschmitt/laravel-amqp#18]
Would be useful to add basic_qos call before basic_consume
especially for prefetch_count option
http://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.qos
https://github.com/php-amqplib/php-amqplib/blob/master/demo/basic_qos.php

Its a must if you want to run a multiple consumer scenario and control the batch size distributed to each consumer (right now the default is 1000 messages).

Currently the simple workaround is to extend \Bschmitt\Amqp\Consumer and add basic_qos call before parent::consume(), after that you just overwrite the bind for \Bschmitt\Amqp\Consumer with your own extended class.
A config option would be more elegant

**Comment by kitekkitek** [comment]
This is actually easy thing to do (tested on large scale for over 4 years now):
in Amqp.php:
```
private $prefetch_count = 1;


public function setPrefetchCount($prefetch_count)
{
    $this->prefetch_count = $prefetch_count;
}

public function consume($queue, Closure $callback, $properties = [])
{
    // If array, binding only first element, then the rest
    $routing_keys = [];
    if (is_array($properties['routing']))
    {
        $routing_keys = $properties['routing'];
        $properties['routing'] = array_shift($routing_keys);
    }

    $properties['queue'] = $queue;
    /* @var Consumer $consumer */
    $consumer = app()->make('Bschmitt\Amqp\Consumer');
    $consumer
        ->mergeProperties($properties)
        ->setup();

    // Binding queue with rest of routing keys
    foreach($routing_keys as $routing_key)
    {
        $consumer->channel->queue_bind($queue ?: $consumer->queueInfo[0], $consumer->getProperty('exchange'), $routing_key);
    }

    // Setting prefetch count
    $consumer->getChannel()->basic_qos(null, $this->prefetch_count, null);

    $consumer->consume($queue, $callback);
    Request::shutdown($consumer->getChannel(), $consumer->getConnection());
}
```

This adds prefetch count and option to pass routing_key as array of routings (multiple bindings per queue). Obviously like FlorinRo said setPrefetchCount() could also be an option `prefetch_count` for consumer.

**Comment by MattBearson** [comment]
@kitekkitek good solution, I made pretty the same but with 3 functions for `prefetch_size`, `prefetch_count` and `a_global`. Well, probably, @bschmitt should add it into `master`. This is a really good improvement.

**Comment by stevenklar** [comment]
@MattBearson if you would like to contribute feel free to open a pull request for this improvement.

**Comment by MattBearson** [comment]
@stevenklar thank you, created a new one pull request few minutes ago

**Comment by stevenklar** [comment]
Feature is done and merged into master. This will be also included in the next tagged release.
