### ISSUE TITLE
5.5 support

### ISSUE THREAD

**Issue by terryzwt** [bschmitt/laravel-amqp#32]
Does this support laravel 5.5?

**Comment by stevenklar** [comment]
It does support laravel 5.5 But you need to add the Provider and Facade yourself.

**Comment by bschmitt** [comment]
In case someone is providing a PR regarding 5.5. compatibility I'd be pleased to merge it into master.

**Comment by stevenklar** [comment]
@bschmitt like this? #34

**Comment by bschmitt** [comment]
@stevenklar thank you very much! Maybe you want to support that project? #41
