### ISSUE TITLE
In cli mode, execute Amqp:: consume, and receive messages for a period of time.

### ISSUE THREAD

**Issue by JayenLee** [bschmitt/laravel-amqp#39]
```
Consume messages forever
Amqp::consume('queue-name', function ($message, $resolver) {
    		
   var_dump($message->body);

   $resolver->acknowledge($message);
        
});
```
This method can't receive MQ server's push any more than a few minutes without receiving the message. What's the problem, please?

**Comment by stevenklar** [comment]
@JayenLee Did you try to change the timeout? Does it effect the mentioned behaviour in any way?
