### ISSUE TITLE
require conflict in Lumen 5.6

### ISSUE THREAD

**Issue by akaQin** [bschmitt/laravel-amqp#42]
Hi，I met some problem when i run "composer require bschmitt/laravel-amqp" in Lumen 5.6, such as following text:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tightenco/collect (locked at v5.6.24) -> satisfiable by tightenco/collect[v5.6.24].
    - bschmitt/laravel-amqp 2.0.0 requires illuminate/support v5.5.28 -> satisfiable by illuminate/support[v5.5.28].
    - bschmitt/laravel-amqp 2.0.1 requires illuminate/support v5.5.28 -> satisfiable by illuminate/support[v5.5.28].
    - Conclusion: don't install illuminate/support v5.5.28
    - Installation request for bschmitt/laravel-amqp ^2.0 -> satisfiable by bschmitt/laravel-amqp[2.0.0, 2.0.1].

Installation failed, reverting ./composer.json to its original content.`

then i found your project require "illuminate/support": "v5.5.28", and Lumen 5.6 require "illuminate/support": "5.6.*",so any suggestion? thanks!

**Comment by stevenklar** [comment]
Hey,

5.6 only supports php 7.1 upwards, which is pretty bad for people still on 5.5 which is >=7.0

So either a full upgrade or seperate branches for 5.5 and 5.6.

**Comment by mirkojotic** [comment]
@stevenklar I gave this a shot. I've forked this repo, updated composer.json to point to a current version of illuminate/support:
`"illuminate/support": "v5.6.24"`
And I've managed to install it in a fresh lumen 5.6.* from a branch on a fork.
Any other things I have to check for?

**Comment by stevenklar** [comment]
@mirkojotic Awesome!

If everything works as expected we might want to use Version ">5.5" which allows laravel 5.5 and 5.6 users to use this package!

Do you recognize any problems?

**Comment by stevenklar** [comment]
Should be fixed with the [latest release](https://github.com/bschmitt/laravel-amqp/releases/tag/2.0.2).
