### ISSUE TITLE
How to use topic?

### ISSUE THREAD

**Issue by JeffreyBool** [bschmitt/laravel-amqp#45]
如果使用 topic  方式怎么去绑定?

**Comment by stevenklar** [comment]
Can you rephrase in english, maybe someone can help you with that question?

**Comment by kenuocn** [comment]
Do you support the topic approach?

**Comment by stevenklar** [comment]
In the README.md is an example with topic.

**Comment by stevenklar** [comment]
@kenuocn What did you already try? Do you have some code to help with?
