### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by CorvinSteindl** [bschmitt/laravel-amqp#46]
Could you please add a example to solve this?
![python-four](https://user-images.githubusercontent.com/13137313/41898169-8b5ac982-7929-11e8-970a-106cb01d94e6.png)
([comes frome here](https://www.rabbitmq.com/tutorials/tutorial-four-php.html))

@stevenklar @bschmitt

**Comment by stevenklar** [comment]
@CorvinSteindl Would you consider open a pull-request with the given example using laravel-amqp?

**Comment by stevenklar** [comment]
@CorvinSteindl I tried to accomplish this and this is totaly possible with the correct configuration and two consumers (one for e. g. info, warning and the other for errors)

If you need specific help, just reopen this issue and I can help you.
