### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Prakashg07** [bschmitt/laravel-amqp#48]
I am following "https://github.com/bschmitt/laravel-amqp" but I am getting "**stream_socket_client(): unable to connect to tcp://localhost:5672 (Connection refused)**". And I have configured amqp.php too

Please help me out here.

**Comment by Prakashg07** [comment]
I solved it. Thanks

**Comment by pawlox** [comment]
Thanks for the solution, really helpful...
