### ISSUE TITLE
Need some suggestion on AMQP Consume

### ISSUE THREAD

**Issue by Prakashg07** [bschmitt/laravel-amqp#50]
I am looking to bind a queue with exchange and routing key while consuming. Do anyone help me out to achieve the above using this (**bschmitt/laravel-amqp**) library?

I have to do something like below:
$binding_key = 'black';
$channel->queue_bind($queue_name, $exchange_name, $binding_key);

Will the below code works:

$connection = new AMQP();
$channel = $connection->channel();
$channel->queue_bind($queue_name, $exchange_name, $binding_key);

Will be great if anyone suggest me with the working code.

**Comment by stevenklar** [comment]
What exactly did you try? Everything you mention is in the documentation?

Down below is also a custom exchange example.
