### ISSUE TITLE
Howto restart after fresh deployed code ?

### ISSUE THREAD

**Issue by Cyrille37** [bschmitt/laravel-amqp#52]
Hi,
Thanks for Ur nice work :-)

Laravel Queues have a `queue:restart` command, to use after deployed fresh code (_usually in composer 'post-install-cmd' event_).
How to do with laravel-amqp when listening forever ?
Is there a way to create command like `laravel-amqp:restart` ?

Thanks & cheers

**Comment by Cyrille37** [comment]
As:
- The Queue Laravel system use the cache `$this->cache->get('illuminate:queue:restart')` to compare date of the last restart, to know if restart is required.
- php-amqplib can handle PCNTL signals

Perhaps one on this recipe could be used ... I continue to search ...

**Comment by stevenklar** [comment]
As far as i'am concerned you need to handle this yourself.
The package itself has no "helper commands" yet and is more like a library you can build on top of.

I would suggest a daemon like supervisord to observe the instance and restart your consumer on deployment.
