### ISSUE TITLE
No version tagged

### ISSUE THREAD

**Issue by SpaceK33z** [bschmitt/laravel-amqp#6]
The readme says that you can add `"bschmitt/laravel-amqp": "1.*"` to your composer file, but this isn't true because no version is tagged. Could you tag a version (maybe `0.1.0`)?

Thanks for this awesome package, we're going to use it a lot.

**Comment by SpaceK33z** [comment]
I see you tagged it, thanks!

**Comment by bschmitt** [comment]
I'm not sure why there is no release on https://packagist.org/packages/bschmitt/laravel-amqp although I've added a tag / release?
