### ISSUE TITLE
Request parameters to AMQPStreamConnection out of order

### ISSUE THREAD

**Issue by jwkblades** [bschmitt/laravel-amqp#60]
The context argument should be [parameter 12, not 11](https://github.com/bschmitt/laravel-amqp/blob/1cb4a4945f2b6beb1f73c31da46ea820f1cf52a5/src/Request.php#L57), for the [AMQPStreamConnection](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AMQPStreamConnection.php), which results in an exception `ErrorException: stream_socket_client() expects parameter 6 to be resource, boolean given`.

Looks like it should just be getting the arguments in the correct order.

**Comment by stevenklar** [comment]
@jwkblades This issue should be fixed with the next release of your merged PR, right?

**Comment by jwkblades** [comment]
Yes, this should be resolved in the next release after my PR.

**Comment by stevenklar** [comment]
Released with tag 2.0.5
