### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given in Context.php line 76

### ISSUE THREAD

**Issue by alupuleasa** [bschmitt/laravel-amqp#64]
Hello,

Function `getProperty()` from `laravel-amqp/src/Context.php` on line 63 returns null when `array_key_exists` returns false . I suggest to modify:

` return array_key_exists($key, $this->properties) ? $this->properties[$key] : null;`
to
` return array_key_exists($key, $this->properties) ? $this->properties[$key] : [];`

to avoid 

`array_key_exists() expects parameter 2 to be array, null given in Context.php line 76`

**Comment by stevenklar** [comment]
Hi @alupuleasa 

thank you for this suggestion. Your'e welcome to patch this in a pull request.
I would be pleased to review and apply it.

Regards
Steven

**Comment by alupuleasa** [comment]
Hi @stevenklar I've made a pull request.

Thank you,
Andrei

**Comment by stevenklar** [comment]
Merged in Release 2.0.6 - Thank you for the contribution. ;-)
