### ISSUE TITLE
@stream_socket_client false in consume

### ISSUE THREAD

**Issue by oleh1231** [bschmitt/laravel-amqp#82]
I have project in one docker container and rabbitmq in another.
In one project I publish and consume message.
For consuming massages I use laravel command.
Publish massage in controller.
When I publish message into queue all work fine, but in the same project consumer  show exception: "Error Connecting to server(0): php_network_getaddresses: getaddrinfo failed: Name does not resolve
".
I configured connection in amqp.php
Part of configuration:
``'host'                  => 'rabbitmq',
            'port'                  => 5672,
            'username'              => 'guest',
            'password'              => 'guest',``

I use laravel 7.

I will be grateful for any help

**Comment by stevenklar** [comment]
Hi @oleh1231 

Your error has nothing to do with this library.
Make sure that both docker container are in the same docker network and the rabbitmq container is running under the name rabbtimq.

Best of luck!

**Comment by oleh1231** [comment]
Hi @stevenklar 
I put containers in the same docker network and all working, thank you
