### ISSUE TITLE
Publish multiple messages - Batch publish

### ISSUE THREAD

**Issue by filipbekic01** [bschmitt/laravel-amqp#91]
I'm having trouble pushing 200+ messages at once. Each publish takes ~2 seconds, that's really slow.

**Comment by joskfg** [comment]
I'm having the same issue and this library doesn't support it. It uses `basic_publish` and there isn't any option to use `batch_basic_publish`.

**Comment by filipbekic01** [comment]
I'd love to extend possibilities but i'm not even sure how active this repository is. I see there are 3 PRs in queue already :-1:

**Comment by bschmitt** [comment]
The library doesn't support *batch_basic_publish* for now. But feel free to provide a PR. There are 3 PRs in review, some of them don't follow the intention of this library.

**Comment by stevenklar** [comment]
Hey Filip, I would love to merge any appropriate enhancement to the
repository.
Just create a PR and follow the repositories purpose.

Thank you :-)

**Comment by joskfg** [comment]
I created a version of this library, with the support. After further testing, I'd like to put here as PR.

**Comment by filipbekic01** [comment]
Do that @joskfg :+1:

**Comment by joskfg** [comment]
Initial approach https://github.com/bschmitt/laravel-amqp/pull/93

**Comment by stevenklar** [comment]
Thank you for the contribution. I would like to merge this for our next release.
Please fix the necessary docblocks and appropriate method scope.

**Comment by joskfg** [comment]
Fixed docblocks and method scope.

**Comment by stevenklar** [comment]
Will be published in the next release.
