### ISSUE TITLE
Version 2.0.11 doesn't work on PHP bellow 7.4 version

### ISSUE THREAD

**Issue by laba97** [bschmitt/laravel-amqp#99]
bschmitt/laravel-amqp/src/Amqp.php
line 14
protected static array $batchMessages = [];

Class properties declaration works only from PHP 7.4, in composer.json there is still PHP >= 7.0 required.

**Comment by bschmitt** [comment]
I would prefer to make it backward compatible. So removing the static typing.

**Comment by mawaraujo** [comment]
Hey, @bschmitt.
Do you have any idea when you will make a release available with this fix?

**Comment by bschmitt** [comment]
@mawaraujo really sorry, release created
